version: '3'
services: 
  algorithm-api:
    build:
      context: api
    image: frlnbrg/project_hopper_algorithm_api
    ports:
    - "80:80"
    restart: always
  
  postgresql:
    build:
      context: .
      dockerfile: Dockerfile-postgres
    ports:
      - "5439:5432"
    environment:
      - POSTGRES_DB=postgresDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=PG_PASS