version: '3'
services: 
  algorithm-api:
    build:
      context: api
    image: frlnbrg/project_knuth_api
    ports:
    - "3080:3080"
    restart: always
  
  pg:
    build:
      context: .
      dockerfile: Dockerfile-postgres
    environment:
      - POSTGRES_DB=postgresDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=PG_PASS